os:
  - linux
  - osx
dist: bionic
osx_image: xcode10.3
language: erlang
otp_release:
  - 21.3
  - 22.0

addons:
  apt:
    packages:
      - libsnappy-dev
  homebrew:
    packages:
      - snappy

cache:
  directories:
    - $HOME/.cache/rebar3
